Computational Methods, Test 1

1. (5 points) Use the following NumPy Arrays to evaluate the Python commands below:



```
x[3] = 2

x[:3] = [3, 6, 7]

y[-1] = 8

y[y>4] = [5, 8, 5, 8]

x[y==8] = [2, 5]
```



In [ ]:
import numpy as np
x = np.array([3, 6, 7, 2, 0, 2, 5, 5])
y = np.array([0, 5, 2, 8, 4, 5, 1, 8])

# enter your code here

2. (5 points) Write down the output of the following commands


In [ ]:
np.linspace(0,5,5) = [0,1.25,2.5,3.75,5]
np.arange(0,10,2) = [0,2,4,6,8]
np.zeros((2,4)) = [0 0 0 0]
                  [0 0 0 0]


3. (5 points) Calculate the sum of the squares of integers from 1 to 100. Use any method.


In [ ]:
sum(i**2 for i in range(1, 101))

4. (5 points) Given a Python list of integers A, create a new list B that only contains those elements of A that are positive. Use a for loop (not logical indexing).


In [ ]:
B = []
for x in A:
    if x > 0:
        B.append(x)

5. (5 points) (a) Write down the output of the following Python program in the box below. Only show what will be printed.

In [ ]:
A = [1, -2, 3, -4, 5, -6]
s1 = 0
s2 = 0
for n in A:
     if n > 0:
         s1 += n
     else:
         s2 += n
     print(f'{n:2} {s1:2} {s2:2}')

In [ ]:
 1  1  0
-2  1 -2
 3  4 -2
-4  4 -6
 5  9 -6
-6  9 -12

6. (5 points) (a) Write down the output of the following Python program in the box below. Only show what will be printed.


In [ ]:
s = 0
for n in range(4):
    for x in range(n+1):
       s += 1
    print(f'{n}  {s}')

In [ ]:
0  1
1  3
2  6
3  10

7. (5 points) Write some Python code using the NumPy library to calculate the speed of an object in free fall:
Prompt the user to enter the height $h$ from which the object is dropped.
Calculate the velocity using $v=\sqrt{2gh}$ , where $g=9.8$ m/s$^2$.
Print a message displaying and labeling the velocity rounded to 2 decimal places
Print a warning message if the speed exceeds half the speed of light, where $c=3\times 10^8$ m/s. The message should read:  “The object is approaching the speed of light”.

In [ ]:
import numpy as np

g = 9.8
c = 3e8

h = float(input("Enter the height (in meters): "))

v = np.sqrt(2 * g * h)

print(f"Velocity of the object: {v:.2f} m/s")

if v > 0.5 * c:
    print("Warning: The object is approaching the speed of light")

Enter the height (in meters): 5
Velocity of the object: 9.90 m/s


8. (5 points) Create a  NumPy array (100 rows and 4 columns) containing the following:
* Column 1:  angle $\theta$ - linearly spaced values between 0 and
* Column 2: $\sin \theta$  
* Column 3: $\cos \theta$
* Column 4:  average of the values in columns 2 and 3

In [ ]:
import numpy as np

theta = np.linspace(0, 2*np.pi, 100)

sin_theta = np.sin(theta)

cos_theta = np.cos(theta)

avg = (sin_theta + cos_theta) / 2

result = np.zeros((100, 4))

result[:, 0] = theta
result[:, 1] = sin_theta
result[:, 2] = cos_theta
result[:, 3] = avg

print(result[:5])

[[0.         0.         1.         0.5       ]
 [0.06346652 0.06342392 0.99798668 0.5307053 ]
 [0.12693304 0.12659245 0.99195481 0.55927363]
 [0.19039955 0.18925124 0.9819287  0.58558997]
 [0.25386607 0.25114799 0.9679487  0.60954834]]


9. (5 points) In this problem, you will explore a random walk in which the motion of a particle is controlled by a coin toss. If the coin is heads, move one unit to the right (+1), if tails, move one unit to the left (–1). Here’s the procedure:
* Ask the user to input the total number of steps for the random walk
* Start the particle at the origin.
* Pick a random number to move the particle left or right by one unit.
* Repeat for a total of N steps
* After the walk is complete, print the position of the particle

     You can use any method you like to solve this problem

In [ ]:
import numpy as np

N = int(input("Enter the total number of steps: "))

position = 0

for _ in range(N):
    step = np.random.choice([-1, 1])
    position += step

print(f"Final position of the particle: {position}")

Enter the total number of steps: 5
Final position of the particle: -1


10. (5 points) The Liebnitz formula for pi is:

$\pi \approx 4 \sum_{k=o}^N \frac{(-1)^k}{2k+1}  \approx 4\cdot \left[ 1-\frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9}+ \cdots \right]$
                             
* Write some Python code that prompts the user for the upper limit on the summation N and calculates the series.
* Calculate the percent error of your approximation:  $error=\left| \frac{estimate-actual}{actual} \right|\times 100\%$

* print your estimated value of pi and the percent error along with a descriptive message
* Use any method you like.

In [ ]:
N = int(input("Enter the number of terms"))

pi_estimate = 0

for k in range(N):
    pi_estimate += (-1)**k / (2*k + 1)

pi_estimate *= 4

pi_actual = 3.141592653589793

error = abs(pi_estimate - pi_actual) / pi_actual * 100

print(f"Estimated value of pi: {pi_estimate}")
print(f"Percent error: {error:.6f}%")

Enter the number of terms6
Estimated value of pi: 2.9760461760461765
Percent error: 5.269508%
